server:
  port: 8085
spring:
  application:
    name: CONFIG-SERVER
  cloud:
    config:
      server:
        git:
          uri: https://github.com/sbokadecred/microservice-tutorial-config
          clone-on-start: true
