server:
  port: 8081

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: microservicess
  application:
     name: HOTEL-SERVICE
  config:
    import: optional:configserver:http://localhost:8085

#eureka:
#  instances:
#    prefer-ip-address: true
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#    service-url:
#      defaultZone: http://localhost:8761/eureka
okta:
  oauth2:
    issuer: https://dev-63254692.okta.com/oauth2/default
    audience: api://default
